---
- name: Ensure stow is installed
  ansible.builtin.package:
    name: stow
    state: present
  become: true

- ansible.builtin.import_tasks: stow-bin.yml
- ansible.builtin.import_tasks: stow-config.yml
- ansible.builtin.import_tasks: stow-shell.yml
