---
- name: Dumpt facts
  ansible.builtin.debug:
    var: "hostvars[inventory_hostname]"

- name: Complex msg
  ansible.builtin.debug:
    # msg: "Facts\n {{ hostvars }}!"
    var: "hostvars"

- name: Env msg
  ansible.builtin.debug:
    # msg: "Facts\n {{ hostvars }}!"
    var: "ansible_facts.env"
