---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{  ansible_facts['distribution'] | lower }}.yml"
# - name: Install common packages
#   become: true
#   ansible.builtin.package:
#     name: "{{ common_packages }}"
#     state: present
- name: Install pacman packages
  become: true
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
    
- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present
- name: "Add EasyEffect profile"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/irs/"
    dest: "{{ ansible_facts['user_dir'] }}/.config/easyeffects/irs/"
    mode: "preserve"
