---
dotfiles_repo: "/home/kamba/dotfiles"

enable_zsh: true
enable_gui_apps: false

git_user_name: "Kamba"
git_user_email: "kamba@laptop.local"

extra_bins: []
hostname: T14

laptop: true
battery_optimization: true
enable_bluetooth: true

gpu: amd
