---
- name: Check for orphaned packages
  become: true
  ansible.builtin.command: "pacman -Qtdq"
  register: orphan_check
  changed_when: false
  failed_when: false

- name: Remove orphaned packages
  become: true
  ansible.builtin.command: >-
    "pacman -Rns --noconfirm {{ orphan_check.stdout_lines | join(' ') }}"
  when: orphan_check.stdout != ""
  register: pacman_cleanup
  changed_when: pacman_cleanup.stdout != ""
  failed_when: false
