---
pacman_packages:
  - git
  - eza
  - jq
  - nodejs
  - npm
  - xsel
  - curl
  - unzip
  - neovim
  - python
  - python-pip
  - fish
  - htop
  - starship
  - zoxide
  - sshfs
  - grex
  - asciinema
  - trash-cli
  - aria2
  - 7zip
  - accountsservice
  - alsa-plugins
  - alsa-utils
  - android-tools
  - ansible
  - ansible-lint
  - autoconf
  - automake
  - autopep8
  - baobab
  - base
  - base-devel
  - bind
  - bison
  - blueman
  - bluez
  - bluez-utils
  - brightnessctl
  - btrfs-progs
  # - clipman
  - copyq
  - deluge
  - deluge-gtk
  - dhcpcd
  - dmidecode
  - docker
  - docker-buildx
  - dosfstools
  # - downgrade
  - dunst
  - easyeffects
  - efibootmgr
  # - exfat-utils
  - faac
  - fakeroot
  - fd
  - file-roller
  - fuse2
  - fuse3
  - fuseiso
  # - gammastep
  - gcc
  - git
  - git-delta
  - git-lfs
  - github-cli
  - gnome-calculator
  - gnome-disk-utility
  - gnome-system-monitor
  - goaccess
  - gparted
  - gptfdisk
  - grim
  - groff
  - gsfonts
  - gst-plugins-good
  - gvfs
  - gvfs-gphoto2
  - gvfs-mtp
  - htop
  - hyprland
  - imagemagick
  - inotify-tools
  - iwd
  - jq
  - keepassxc
  - kooha
  - lftp
  # - libinput-gestures
  - libpulse
  - libtool
  - linux-firmware
  - linux-zen
  - linux-zen-headers
  - lsof
  - lzop
  - m4
  - make
  - man-db
  - mediainfo
  - mpv
  - mtools
  - mtpfs
  - neovim
  - network-manager-applet
  - networkmanager
  - networkmanager-openvpn
  - nmap
  - nodejs
  - npm
  - ntfs-3g
  - ntp
  - nwg-look
  - openssh
  - openvpn
  - pacman-contrib
  - patch
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  # - pix
  - pkgconf
  - playerctl
  - python-openai
  - python-passlib
  - python-pip
  - python-uv
  - python-virtualenv
  - remmina
  - ripgrep
  # - rsynci
  - smartmontools
  - sof-firmware
  - sshfs
  - sudo
  - syncthing
  # - systemd-resolvconf
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  # - tlp
  - tmux
  - tomlplusplus
  - traceroute
  - tumbler
  - unrar
  - unzip
  - usbutils
  - wavpack
  - waybar
  - wget
  - which
  - wireguard-tools
  - wireless_tools
  - wireplumber
  - wl-clipboard
  - wofi
  # - wrk
  - xdg-desktop-portal-hyprland
  - xdg-user-dirs
  - xdg-utils
  - yarn
  - zip
  - zram-generator
  - zsh
  - rofi-wayland
  - tree-sitter-cli
  - cava
  - fuzzel
  - cyme
aur_packages:
  - arc-gtk-theme
  - betterbird-bin
  - claude-desktop-native
  - chatbox-bin
  - google-chrome
  - grimblast-git
  - obsidian
  - oh-my-posh
  - os-prober-btrfs
  - shellcheck-bin
  - signal-desktop
  - syncthingtray
  - taskwarrior-tui
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-droid
  - ttf-fira-code
  - ttf-fira-sans
  - ttf-firacode-nerd
  - ttf-font-awesome
  - ttf-font-awesome-4
  - ttf-jetbrains-mono
  - ttf-jetbrains-mono-nerd
  - ttf-liberation
  - ttf-ms-fonts
  - ttf-nerd-fonts-symbols
  - ttf-ubuntu-font-family
  - woff2-font-awesome
  - yay
  - downgrade 
  - gearlever  
  - nemo-compare
  - pacseek                      
  - ente-auth-bin                 
