base.aur_pkgs:
- downgrade
- gearlever
- nemo-compare
- pacseek
- ente-auth-bin
base.nix:
- with
- fd
- neovim
- ripgrep
- eza
- ']'
base.pkgs:
- atuin
- btop
- coreutils
- fd
- findutils
- firefox
- fzf
- ghostty
- git
- git-lfs
- glibc
- gnupg
- gum
- gvfs-dnssd
- kitty
- ld-lsb
- linux-lts
- mkinitcpio
- nemo
- nemo-audio-tab
- nemo-fileroller
- nemo-preview
- pkgfile
- python
- ripgrep
- ttf-jetbrains-mono-nerd
- ttf-nerd-fonts-symbols-mono
- ttf-comic-mono-git
- ttf-comic-neue
- unzip
- zip
- zsh
debian.pkgs:
- '#'
- bat
- gum
- neovim
- stow
- software-properties-common
- zoxide
- fzf
- zip
- unzip
dev.aur_pkgs:
- '#'
- '#ltex-ls'
- 1password-cli
- bottles
- devtoys-bin
- drawio-desktop
- fast-bin
- git-credential-manager
- git-credential-oauth
- gitkraken
- gpgfrontend
- pacseek
- sshs
- wifi-qr
- zsh-vi-mode
dev.pkgs:
- age
- base-devel
- bash-completion
- bat
- binsider
- chromium
- clang
- cloc
- cool-retro-term
- direnv
- doxygen
- element-desktop
- eza
- fastfetch
- fd
- firefox
- flatpak
- ghex
- git-crypt
- git-delta
- github-cli
- glow
- gnome-boxes
- hugo
- imagemagick
- jupyterlab
- just
- kate
- kitty
- lazygit
- marksman
- meld
- mesa-utils
- moreutils
- neovim
- netscanner
- nmap
- obsidian
- openssh
- pacman-contrib
- pandoc-cli
- pastebin
- powertop
- python
- python-adblock
- qalculate-gtk
- qbittorrent
- qt5ct
- qt6ct
- qutebrowser
- remmina
- ripgrep
- ripgrep-all
- rsync
- rust-analyzer
- rustup
- serie
- speedcrunch
- spotify-launcher
- television
- termdown
- thefuck
- tldr
- torbrowser-launcher
- tree
- veracrypt
- wine
- yq
- yt-dlp
- yt-dlp-ejs
- zed
- zellij
- zoxide
- zsh
- zsh-autosuggestions
- zsh-completions
- zsh-syntax-highlighting
hyprland.aur_pkgs:
- '#index-fm'
- adwaita-dark
- adwaita-qt5-git
- adwaita-qt6-git
- bemoji
- cava
- clipman
- hyprpicker
- hyprshade
- hyprshot
- hyprswitch
- jome-git
- musikcube
- nmgui-bin
- nwg-displays
- pacseek
- peaclock
- qview
- timer-bin
- tokyonight-gtk-theme-git
- unipicker
- wallust
- wayland-logout
- waypaper
- webapp-manager
- wlogout
- zen-browser-bin
hyprland.pkgs:
- archlinux-xdg-menu
- blueman
- bluez
- brightnessctl
- cliphist
- copyq
- dunst
- fastfetch
- fuzzel
- gcolor3
- gnome-disk-utility
- gnome-keyring
- gnome-themes-extra
- grim
- hypridle
- hyprland
- hyprlock
- hyprpaper
- hyprpolkitagent
- hyprsunset
- kvantum
- kwallet
- kwalletmanager
- mission-center
- mpv
- network-manager-applet
- networkmanager
- nwg-look
- pavucontrol
- pipewire
- polkit-kde-agent
- qt5ct
- qt6ct
- sddm
- seahorse
- slurp
- spotify-launcher
- starship
- swappy
- termdown
- ttf-jetbrains-mono-nerd
- waybar
- wireplumber
- wl-clipboard
- wofi
- wtype
- xbindkeys
- xdg-desktop-portal-hyprland
- yazi
- zathura
- zathura-cb
- zathura-pdf-mupdf
kde-plasma.aur_pkgs:
- 1password
- 1password-cli
- adwaita-dark
- adwaita-qt5-git
- adwaita-qt6-git
- ''
kde-plasma.pkgs:
- blueman
- fastfetch
- gcolor3
- kde-applications
- kmenuedit
- kvantum
- kwallet
- kwalletmanager
- mpv
- pavucontrol
- pipewire
- plasma
- plasma-wayland-session
- polkit-kde-agent
- qt5ct
- qt6ct
- sddm
- seahorse
- spotify-launcher
- starship
- ttf-jetbrains-mono-nerd
- wireplumber
- wl-clipboard
- wtype
- xbindkeys
- xdg-desktop-portal-hyprland
- yazi
- zathura
- zathura-cb
- zathura-pdf-mupdf
latex.pkgs:
- texinfo
- texlab
- texlive-basic
- texlive-bibtexextra
- texlive-binextra
- texlive-context
- texlive-fontsextra
- texlive-fontsrecommended
- texlive-fontutils
- texlive-formatsextra
- texlive-games
- texlive-humanities
- texlive-langenglish
- texlive-langgerman
- texlive-latex
- texlive-latexextra
- texlive-latexrecommended
- texlive-luatex
- texlive-mathscience
- texlive-metapost
- texlive-music
- texlive-pictures
- texlive-plaingeneric
- texlive-pstricks
- texlive-publishers
- texlive-xetex
- texlive-langgreek
office.aur_pkgs:
- '#superfile'
- '#index-fm'
- 1password
- anki
- decoder
- gpgfrontend
- localsend-bin
- parabolic
- peazip-qt-bin
- ticktick
- wifi-qr
office.pkgs:
- age
- calibre
- ghostwriter
- gimp
- glow
- gwenview
- haruna
- hugo
- imagemagick
- inkscape
- korganizer
- obsidian
- okular
- pastebin
- pdfgrep
- pinta
- poppler-glib
- print-manager
- signal-desktop
- thunderbird
- veracrypt
termux.pkgs:
- atuin
- eza
- fzf
- git
- just
- lazygit
- neovim
- openssh-sftp-server
- rust
- starship
- stow
- termux-api
- yazi
- zoxide
- zsh
uni.aur_pkgs:
- anki
- python-pympress
- zotero
uni.pkgs:
- curtail
- pdfgrep
- pinta
