- name: Install base packages (official repos + AUR)
  tags: base
  community.general.pacman:
    name: "{{ pkgs + aur_pkgs }}"
    state: present
    update_cache: yes
    executable: yay
    # become: true
- name: Install development packages (official + AUR)
  tags: dev
  ignore_errors: yes
  community.general.pacman:
    name: "{{ pkgs_dev + aur_pkgs_dev }}"
    state: present
    update_cache: yes
    executable: yay
    # become: true
- name: Install Hyprland-related packages (official + AUR)
  tags: hyprland
  ignore_errors: yes
  community.general.pacman:
    name: "{{ignore_errors: yes hyprland_pkgs + hyprland_aur_pkgs }}"
    state: present
    update_cache: yes
    executable: yay
    # become: true
- name: Install office/productivity packages (official + AUR)
  tags: office
  ignore_errors: yes
  community.general.pacman:
    name: "{{ office_pkgs + office_aur_pkgs }}"
    state: present
    update_cache: yes
    executable: yay
    # become: true
- name: Install university-specific packages (official + AUR)
  tags: uni
  ignore_errors: yes
  community.general.pacman:
    name: "{{ uni_pkgs + uni_aur_pkgs }}"
    state: present
    update_cache: yes
    executable: yay
    # become: true
- name: Full system upgrade (including AUR packages)
  tags: upgrade
  ignore_errors: yes
  community.general.pacman:
    upgrade: yes
    update_cache: yes
    executable: yay
  # become: true
